### ISSUE TITLE
[EPIC] nucypher-ts MVP

### ISSUE THREAD

**Issue by piotr-roslaniec** [nucypher/nucypher-ts#2]
This is a rough draft of several `nucypher/nucypher-ts` modules in an attempt to tie together a boilerplate for the rest of the library.

The idea is to reimplement existing `nucypher/nucypher` flows using Porter as a replacement for all network interactions. I will be using acceptance and integration tests from `nucypher` as a reference point. The code borrows heavily from `nucypher/nucypher` codebase, especially abstractions such as policies, crypto powers, keyrings, etc.

The goal is to have at least one "user story" working. A lot of implementations will be stubbed-out initially, especially ones related to Porter or blockchain transactions. 

Further down the road, `nucypher/NuSnap` will be updated to implement  `nucypher/nucypher-ts`.

The design of the user-facing library is not final and will be rewritten heavily. As always, all comments are welcome!

### To Do
- [x] Implement a use story - "Alice grants access to Bob through a new blockchain policy"
   - [x] Alice / Enrico encrypts a message
   - [x] Alice creates a blockchain policy
   - [x] Alice publishes blockchain policy to blockchain
   - [x] Bob retrieves treasure map from ~~blockchain policy~~ sidechannel
   - [x] Bob retrieves capsule fragments 
   - [x] Bob decrypts the message
- [x] Characters
  - [x] Alice
  - [x] Bob
  - [x] Porter
  - [x] ~~Ursula~~ Currently replaced with Porter proxy
  - [x] Enrico
- [x] Ethereum
  - [x] Web3 client
  - [x] Contracts
- [x] Crypto - Review selection of js libs
  - [x] ~~HKDF with Blake2 (64)~~ Using keccak256 for now
  - [x] Keccak256
  - [x] ECDSA
  - [x] SHA256
- [x] ~~Should `nucypher-ts` be browser and Node.js compatible?~~ Focus on browser compatibility 
- [x] Utilities
  - [x] Compatibility with Serialization (Bytesplitter)
  - [x] Compatibility with NuCypher constants (`constant-sorrow`)
- [x] Design decisions (user API)
    - [x] Handling transactions, web3 provider
    - [x]  Remove `Buffer` usage
 - [x] Cryptopowers: 
     - [x] ~~Interface with NuSnap~~  Postponed
     - [x] Instantiate from seed (secret ket), `fromSecretKey` 
     - [x] ~~Instantiate from web3 provider, `fromWeb3`~~ Connect a web3 provider instead
 
### Relevant PRs
- #3 
- #4
- #5
- #7
- #12     
- #16
